const env = import.meta.env;

const SUPABASE_API_KEY = env.VITE_SUPABASE_API_KEY;
const SUPABASE_AUTHORIZATION_TOKEN = env.VITE_SUPABASE_AUTHORIZATION_TOKEN;
const BACKEND_ENDPOINT = env.VITE_BACKEND_ENDPOINT;

export { SUPABASE_API_KEY, SUPABASE_AUTHORIZATION_TOKEN, BACKEND_ENDPOINT };